import { MealModel } from '../models/MealModel';

export const seedMeals = async () => {
  try {
    const existingCount = await MealModel.countDocuments();
    if (existingCount > 0) {
      console.log(`ℹ️ Meal Database already populated with ${existingCount} items. Skipping meal seed.`);
      return;
    }

    const mealsData = [
      // BREAKFAST OPTIONS
      {
        name: 'High-Protein Oats with Berries & Almond Butter',
        mealType: 'breakfast',
        category: 'High Protein',
        dietaryPreference: 'Vegetarian',
        suitableGoals: ['weight_loss', 'muscle_gain', 'maintenance'],
        allergens: ['Nuts'],
        calories: 380,
        protein: 22.0,
        carbohydrates: 48.0,
        fat: 11.0,
        fiber: 8.0,
        servingSize: 300,
        servingUnit: 'g',
        ingredients: ['Rolled Oats', 'Whey Protein Powder', 'Almond Butter', 'Blueberries', 'Chia Seeds'],
        instructions: 'Cook oats in hot almond milk, stir in protein powder, top with berries and nut butter.',
        isVerified: true,
      },
      {
        name: 'Avocado & Egg Toast on Sprouted Whole Grain',
        mealType: 'breakfast',
        category: 'Balanced Healthy',
        dietaryPreference: 'Vegetarian',
        suitableGoals: ['weight_loss', 'maintenance'],
        allergens: ['Eggs', 'Gluten'],
        calories: 320,
        protein: 16.0,
        carbohydrates: 28.0,
        fat: 16.0,
        fiber: 7.0,
        servingSize: 200,
        servingUnit: 'g',
        ingredients: ['Whole Grain Sprouted Toast', 'Poached Eggs', 'Hass Avocado', 'Microgreens', 'Chili Flakes'],
        instructions: 'Toast bread, mash fresh avocado with sea salt and lemon juice, top with poached eggs.',
        isVerified: true,
      },
      {
        name: 'Masala Tofu Scramble with Spinach & Mushrooms',
        mealType: 'breakfast',
        category: 'Vegan High Protein',
        dietaryPreference: 'Vegan',
        suitableGoals: ['weight_loss', 'muscle_gain', 'maintenance'],
        allergens: ['Soy'],
        calories: 290,
        protein: 24.0,
        carbohydrates: 12.0,
        fat: 15.0,
        fiber: 5.0,
        servingSize: 250,
        servingUnit: 'g',
        ingredients: ['Firm Tofu', 'Baby Spinach', 'Button Mushrooms', 'Turmeric', 'Nutritional Yeast'],
        instructions: 'Crumble tofu into olive oil, sauté with turmeric, cumin, mushrooms, and fresh spinach.',
        isVerified: true,
      },
      {
        name: 'Mass-Gainer Banana Peanut Butter Smoothie Bowl',
        mealType: 'breakfast',
        category: 'Calorie Surplus',
        dietaryPreference: 'Vegetarian',
        suitableGoals: ['weight_gain', 'muscle_gain'],
        allergens: ['Nuts', 'Dairy'],
        calories: 680,
        protein: 35.0,
        carbohydrates: 85.0,
        fat: 22.0,
        fiber: 9.0,
        servingSize: 450,
        servingUnit: 'g',
        ingredients: ['Ripe Bananas', 'Peanut Butter', 'Greek Yogurt', 'Whole Milk', 'Honey', 'Granola'],
        instructions: 'Blend bananas, yogurt, milk, and peanut butter until thick. Serve topped with crisp granola.',
        isVerified: true,
      },

      // LUNCH OPTIONS
      {
        name: 'Grilled Herb Chicken Breast with Quinoa & Asparagus',
        mealType: 'lunch',
        category: 'Lean Protein',
        dietaryPreference: 'Non-Vegetarian',
        suitableGoals: ['weight_loss', 'muscle_gain', 'maintenance'],
        allergens: [],
        calories: 460,
        protein: 42.0,
        carbohydrates: 38.0,
        fat: 12.0,
        fiber: 6.0,
        servingSize: 350,
        servingUnit: 'g',
        ingredients: ['Chicken Breast', 'Cooked Quinoa', 'Steamed Asparagus', 'Olive Oil', 'Garlic & Rosemary'],
        instructions: 'Grill chicken breast with olive oil and rosemary. Serve over fluffy quinoa with asparagus.',
        isVerified: true,
      },
      {
        name: 'Mediterranean Chickpea & Feta Power Bowl',
        mealType: 'lunch',
        category: 'High Fiber',
        dietaryPreference: 'Vegetarian',
        suitableGoals: ['weight_loss', 'maintenance'],
        allergens: ['Dairy'],
        calories: 420,
        protein: 18.0,
        carbohydrates: 54.0,
        fat: 15.0,
        fiber: 12.0,
        servingSize: 320,
        servingUnit: 'g',
        ingredients: ['Chickpeas', 'Cucumbers', 'Cherry Tomatoes', 'Crumble Feta Cheese', 'Kalamata Olives'],
        instructions: 'Toss chickpeas with cucumbers, tomatoes, feta cheese, and extra virgin olive oil.',
        isVerified: true,
      },
      {
        name: 'Salmon Poke Bowl with Brown Rice & Edamame',
        mealType: 'lunch',
        category: 'Omega-3 Rich',
        dietaryPreference: 'Pescatarian',
        suitableGoals: ['muscle_gain', 'weight_gain', 'maintenance'],
        allergens: ['Seafood', 'Soy', 'Sesame'],
        calories: 590,
        protein: 36.0,
        carbohydrates: 62.0,
        fat: 20.0,
        fiber: 7.0,
        servingSize: 380,
        servingUnit: 'g',
        ingredients: ['Fresh Salmon', 'Brown Jasmine Rice', 'Steamed Edamame', 'Avocado Slice', 'Sesame Soy Dressing'],
        instructions: 'Assemble warm brown rice base, top with fresh diced salmon, edamame, and avocado.',
        isVerified: true,
      },

      // DINNER OPTIONS
      {
        name: 'Baked Pan-Seared Salmon with Sweet Potato Mash',
        mealType: 'dinner',
        category: 'Healthy Fats',
        dietaryPreference: 'Pescatarian',
        suitableGoals: ['weight_loss', 'muscle_gain', 'maintenance'],
        allergens: ['Seafood'],
        calories: 490,
        protein: 35.0,
        carbohydrates: 34.0,
        fat: 22.0,
        fiber: 5.0,
        servingSize: 340,
        servingUnit: 'g',
        ingredients: ['Atlantic Salmon Fillet', 'Mashed Sweet Potato', 'Steamed Broccoli', 'Lemon Herb Oil'],
        instructions: 'Sear salmon skin-side down for 4 mins, bake sweet potato and steam fresh broccoli florets.',
        isVerified: true,
      },
      {
        name: 'Lentil & Vegetable Shepherd’s Pie (Vegan)',
        mealType: 'dinner',
        category: 'Comfort Vegan',
        dietaryPreference: 'Vegan',
        suitableGoals: ['weight_loss', 'maintenance'],
        allergens: [],
        calories: 380,
        protein: 19.0,
        carbohydrates: 58.0,
        fat: 8.0,
        fiber: 14.0,
        servingSize: 360,
        servingUnit: 'g',
        ingredients: ['Brown Lentils', 'Carrots', 'Green Peas', 'Yukon Gold Potato Topping', 'Vegetable Broth'],
        instructions: 'Simmer lentils and veggies in savory herbs, top with mashed potatoes and bake until golden.',
        isVerified: true,
      },
      {
        name: 'Lean Beef Tenderloin Stir-Fry with Jasmine Rice',
        mealType: 'dinner',
        category: 'High Protein Surplus',
        dietaryPreference: 'Non-Vegetarian',
        suitableGoals: ['muscle_gain', 'weight_gain'],
        allergens: ['Soy', 'Sesame'],
        calories: 640,
        protein: 48.0,
        carbohydrates: 65.0,
        fat: 20.0,
        fiber: 4.0,
        servingSize: 420,
        servingUnit: 'g',
        ingredients: ['Grass-Fed Beef Tenderloin', 'Jasmine Rice', 'Bell Peppers', 'Snap Peas', 'Tamari Sauce'],
        instructions: 'Wok-fry sliced beef strips with bell peppers and ginger tamari, serve hot over steamed jasmine rice.',
        isVerified: true,
      },

      // SNACK OPTIONS
      {
        name: 'High-Protein Greek Yogurt Parfait',
        mealType: 'snack',
        category: 'Quick Protein',
        dietaryPreference: 'Vegetarian',
        suitableGoals: ['weight_loss', 'muscle_gain', 'maintenance'],
        allergens: ['Dairy'],
        calories: 180,
        protein: 18.0,
        carbohydrates: 16.0,
        fat: 3.5,
        fiber: 3.0,
        servingSize: 180,
        servingUnit: 'g',
        ingredients: ['0% Fat Plain Greek Yogurt', 'Fresh Raspberries', 'Drizzle Raw Honey', 'Flaxseed Meal'],
        instructions: 'Layer thick Greek yogurt in glass bowl with raspberries and ground flaxseed meal.',
        isVerified: true,
      },
      {
        name: 'Roasted Edamame & Sea Salt Crunch',
        mealType: 'snack',
        category: 'Plant Snack',
        dietaryPreference: 'Vegan',
        suitableGoals: ['weight_loss', 'maintenance'],
        allergens: ['Soy'],
        calories: 140,
        protein: 13.0,
        carbohydrates: 10.0,
        fat: 5.0,
        fiber: 6.0,
        servingSize: 100,
        servingUnit: 'g',
        ingredients: ['Green Edamame Beans', 'Avocado Oil Spray', 'Coarse Sea Salt'],
        instructions: 'Dry roast edamame in oven at 200°C for 20 mins until crisp and season lightly with sea salt.',
        isVerified: true,
      },
      {
        name: 'Nut & Seed Energy Protein Bombs',
        mealType: 'snack',
        category: 'Energy Dense',
        dietaryPreference: 'Vegan',
        suitableGoals: ['weight_gain', 'muscle_gain'],
        allergens: ['Nuts'],
        calories: 260,
        protein: 9.0,
        carbohydrates: 24.0,
        fat: 15.0,
        fiber: 4.0,
        servingSize: 80,
        servingUnit: 'g',
        ingredients: ['Medjool Dates', 'Almond Butter', 'Hemp Hearts', 'Dark Chocolate Chips', 'Rolled Oats'],
        instructions: 'Process dates and nut butter, roll into compact bites, and chill in refrigerator.',
        isVerified: true,
      },
    ];

    await MealModel.insertMany(mealsData);
    console.log(`✅ Successfully seeded ${mealsData.length} curated meals into database.`);
  } catch (error) {
    console.error('⚠️ Error seeding meal database:', error);
  }
};
