import { FoodModel } from '../models/FoodModel';

export const seedFoodsDatabase = async () => {
  try {
    const existingCount = await FoodModel.countDocuments();
    if (existingCount > 0) {
      console.log(`ℹ️ Food database already seeded (${existingCount} items present).`);
      return;
    }

    const foodsData = [
      {
        name: 'Grilled Chicken Breast',
        category: 'Poultry & Meat',
        brand: 'Fresh Choice',
        servingSize: 100,
        servingUnit: 'g',
        servingOptions: [
          { amount: 100, unit: 'g', label: '100 grams' },
          { amount: 150, unit: 'g', label: '1 Medium Breast (150g)' },
          { amount: 200, unit: 'g', label: '1 Large Breast (200g)' },
        ],
        calories: 165,
        protein: 31.0,
        carbohydrates: 0.0,
        fat: 3.6,
        fiber: 0.0,
        sugar: 0.0,
        sodium: 74,
        vitaminsAndMinerals: [
          { name: 'Vitamin B6', amount: 0.6, unit: 'mg', dailyValuePercentage: 35 },
          { name: 'Vitamin B12', amount: 0.3, unit: 'mcg', dailyValuePercentage: 13 },
          { name: 'Niacin (B3)', amount: 13.7, unit: 'mg', dailyValuePercentage: 85 },
          { name: 'Phosphorus', amount: 228, unit: 'mg', dailyValuePercentage: 23 },
          { name: 'Potassium', amount: 256, unit: 'mg', dailyValuePercentage: 6 },
          { name: 'Iron', amount: 1.0, unit: 'mg', dailyValuePercentage: 6 },
        ],
        dataSource: 'USDA FoodData Central',
        isVerified: true,
      },
      {
        name: 'Fresh Red Apple',
        category: 'Fruits',
        brand: 'Orchard Fresh',
        servingSize: 100,
        servingUnit: 'g',
        servingOptions: [
          { amount: 100, unit: 'g', label: '100 grams' },
          { amount: 182, unit: 'medium', label: '1 Medium Apple (182g)' },
          { amount: 240, unit: 'large', label: '1 Large Apple (240g)' },
        ],
        calories: 52,
        protein: 0.3,
        carbohydrates: 13.8,
        fat: 0.2,
        fiber: 2.4,
        sugar: 10.4,
        sodium: 1,
        vitaminsAndMinerals: [
          { name: 'Vitamin C', amount: 4.6, unit: 'mg', dailyValuePercentage: 8 },
          { name: 'Vitamin A', amount: 54, unit: 'IU', dailyValuePercentage: 1 },
          { name: 'Potassium', amount: 107, unit: 'mg', dailyValuePercentage: 3 },
          { name: 'Calcium', amount: 6, unit: 'mg', dailyValuePercentage: 1 },
          { name: 'Magnesium', amount: 5, unit: 'mg', dailyValuePercentage: 1 },
        ],
        dataSource: 'USDA FoodData Central',
        isVerified: true,
      },
      {
        name: 'Steamed Brown Rice',
        category: 'Grains & Cereals',
        brand: 'Organic Harvest',
        servingSize: 100,
        servingUnit: 'g',
        servingOptions: [
          { amount: 100, unit: 'g', label: '100 grams' },
          { amount: 195, unit: 'cup', label: '1 Cooked Cup (195g)' },
        ],
        calories: 112,
        protein: 2.6,
        carbohydrates: 23.5,
        fat: 0.9,
        fiber: 1.8,
        sugar: 0.4,
        sodium: 5,
        vitaminsAndMinerals: [
          { name: 'Manganese', amount: 1.1, unit: 'mg', dailyValuePercentage: 55 },
          { name: 'Magnesium', amount: 43, unit: 'mg', dailyValuePercentage: 11 },
          { name: 'Phosphorus', amount: 83, unit: 'mg', dailyValuePercentage: 8 },
          { name: 'Vitamin B6', amount: 0.1, unit: 'mg', dailyValuePercentage: 7 },
          { name: 'Iron', amount: 0.4, unit: 'mg', dailyValuePercentage: 2 },
        ],
        dataSource: 'USDA FoodData Central',
        isVerified: true,
      },
      {
        name: 'Avocado (Hass)',
        category: 'Fruits & Healthy Fats',
        brand: 'Farm Fresh',
        servingSize: 100,
        servingUnit: 'g',
        servingOptions: [
          { amount: 100, unit: 'g', label: '100 grams' },
          { amount: 150, unit: 'medium', label: '1 Medium Avocado (150g)' },
          { amount: 50, unit: 'half', label: 'Half Avocado (50g)' },
        ],
        calories: 160,
        protein: 2.0,
        carbohydrates: 8.5,
        fat: 14.7,
        fiber: 6.7,
        sugar: 0.7,
        sodium: 7,
        vitaminsAndMinerals: [
          { name: 'Vitamin K', amount: 21.0, unit: 'mcg', dailyValuePercentage: 26 },
          { name: 'Folate (B9)', amount: 81.0, unit: 'mcg', dailyValuePercentage: 20 },
          { name: 'Vitamin C', amount: 10.0, unit: 'mg', dailyValuePercentage: 17 },
          { name: 'Potassium', amount: 485, unit: 'mg', dailyValuePercentage: 14 },
          { name: 'Vitamin E', amount: 2.07, unit: 'mg', dailyValuePercentage: 10 },
          { name: 'Vitamin B6', amount: 0.26, unit: 'mg', dailyValuePercentage: 13 },
        ],
        dataSource: 'USDA FoodData Central',
        isVerified: true,
      },
      {
        name: 'Atlantic Salmon Fillet (Pan-Seared)',
        category: 'Seafood',
        brand: 'Ocean Catch',
        servingSize: 100,
        servingUnit: 'g',
        servingOptions: [
          { amount: 100, unit: 'g', label: '100 grams' },
          { amount: 170, unit: 'fillet', label: '1 Medium Fillet (170g)' },
        ],
        calories: 206,
        protein: 22.1,
        carbohydrates: 0.0,
        fat: 12.3,
        fiber: 0.0,
        sugar: 0.0,
        sodium: 61,
        vitaminsAndMinerals: [
          { name: 'Vitamin B12', amount: 3.2, unit: 'mcg', dailyValuePercentage: 133 },
          { name: 'Vitamin D', amount: 526, unit: 'IU', dailyValuePercentage: 66 },
          { name: 'Selenium', amount: 36.5, unit: 'mcg', dailyValuePercentage: 66 },
          { name: 'Niacin (B3)', amount: 8.5, unit: 'mg', dailyValuePercentage: 53 },
          { name: 'Potassium', amount: 363, unit: 'mg', dailyValuePercentage: 10 },
          { name: 'Omega-3 Fatty Acids', amount: 2.3, unit: 'g', dailyValuePercentage: 100 },
        ],
        dataSource: 'USDA FoodData Central',
        isVerified: true,
      },
      {
        name: 'Greek Yogurt (Plain Low-Fat)',
        category: 'Dairy',
        brand: 'Dairy Pure',
        servingSize: 100,
        servingUnit: 'g',
        servingOptions: [
          { amount: 100, unit: 'g', label: '100 grams' },
          { amount: 170, unit: 'container', label: '1 Single Tub (170g)' },
        ],
        calories: 73,
        protein: 10.0,
        carbohydrates: 3.9,
        fat: 1.9,
        fiber: 0.0,
        sugar: 3.6,
        sodium: 36,
        vitaminsAndMinerals: [
          { name: 'Calcium', amount: 110, unit: 'mg', dailyValuePercentage: 11 },
          { name: 'Vitamin B12', amount: 0.75, unit: 'mcg', dailyValuePercentage: 31 },
          { name: 'Riboflavin (B2)', amount: 0.28, unit: 'mg', dailyValuePercentage: 21 },
          { name: 'Phosphorus', amount: 135, unit: 'mg', dailyValuePercentage: 14 },
          { name: 'Zinc', amount: 0.52, unit: 'mg', dailyValuePercentage: 5 },
        ],
        dataSource: 'USDA FoodData Central',
        isVerified: true,
      },
      {
        name: 'Raw Spinach',
        category: 'Vegetables & Greens',
        brand: 'Organic Greens',
        servingSize: 100,
        servingUnit: 'g',
        servingOptions: [
          { amount: 100, unit: 'g', label: '100 grams' },
          { amount: 30, unit: 'cup', label: '1 Raw Cup (30g)' },
        ],
        calories: 23,
        protein: 2.9,
        carbohydrates: 3.6,
        fat: 0.4,
        fiber: 2.2,
        sugar: 0.4,
        sodium: 79,
        vitaminsAndMinerals: [
          { name: 'Vitamin A', amount: 9377, unit: 'IU', dailyValuePercentage: 188 },
          { name: 'Vitamin K', amount: 483, unit: 'mcg', dailyValuePercentage: 604 },
          { name: 'Vitamin C', amount: 28.1, unit: 'mg', dailyValuePercentage: 47 },
          { name: 'Folate (B9)', amount: 194, unit: 'mcg', dailyValuePercentage: 49 },
          { name: 'Manganese', amount: 0.9, unit: 'mg', dailyValuePercentage: 45 },
          { name: 'Magnesium', amount: 79, unit: 'mg', dailyValuePercentage: 20 },
          { name: 'Iron', amount: 2.7, unit: 'mg', dailyValuePercentage: 15 },
          { name: 'Potassium', amount: 558, unit: 'mg', dailyValuePercentage: 16 },
        ],
        dataSource: 'USDA FoodData Central',
        isVerified: true,
      },
      {
        name: 'Whole Large Egg (Boiled)',
        category: 'Proteins',
        brand: 'Farm Eggs',
        servingSize: 50,
        servingUnit: 'g',
        servingOptions: [
          { amount: 50, unit: 'large_egg', label: '1 Large Egg (50g)' },
          { amount: 100, unit: 'g', label: '100 grams (2 Eggs)' },
        ],
        calories: 78,
        protein: 6.3,
        carbohydrates: 0.6,
        fat: 5.3,
        fiber: 0.0,
        sugar: 0.6,
        sodium: 62,
        vitaminsAndMinerals: [
          { name: 'Choline', amount: 147, unit: 'mg', dailyValuePercentage: 27 },
          { name: 'Vitamin B12', amount: 0.6, unit: 'mcg', dailyValuePercentage: 23 },
          { name: 'Vitamin D', amount: 44, unit: 'IU', dailyValuePercentage: 11 },
          { name: 'Vitamin A', amount: 260, unit: 'IU', dailyValuePercentage: 5 },
          { name: 'Selenium', amount: 15.4, unit: 'mcg', dailyValuePercentage: 22 },
          { name: 'Riboflavin (B2)', amount: 0.2, unit: 'mg', dailyValuePercentage: 15 },
        ],
        dataSource: 'USDA FoodData Central',
        isVerified: true,
      },
      {
        name: 'Dal Tadka (Yellow Lentil Curry)',
        category: 'Indian Staples',
        brand: 'Home Style',
        servingSize: 100,
        servingUnit: 'g',
        servingOptions: [
          { amount: 100, unit: 'g', label: '100 grams' },
          { amount: 200, unit: 'bowl', label: '1 Medium Bowl (200g)' },
        ],
        calories: 118,
        protein: 6.2,
        carbohydrates: 16.4,
        fat: 3.1,
        fiber: 4.2,
        sugar: 1.1,
        sodium: 320,
        vitaminsAndMinerals: [
          { name: 'Folate (B9)', amount: 95, unit: 'mcg', dailyValuePercentage: 24 },
          { name: 'Iron', amount: 2.1, unit: 'mg', dailyValuePercentage: 12 },
          { name: 'Potassium', amount: 290, unit: 'mg', dailyValuePercentage: 8 },
          { name: 'Magnesium', amount: 32, unit: 'mg', dailyValuePercentage: 8 },
          { name: 'Zinc', amount: 1.1, unit: 'mg', dailyValuePercentage: 10 },
        ],
        dataSource: 'Indian Food Composition Tables',
        isVerified: true,
      },
      {
        name: 'Paneer Tikka (Grilled Cottage Cheese)',
        category: 'Indian Staples',
        brand: 'Chef Special',
        servingSize: 100,
        servingUnit: 'g',
        servingOptions: [
          { amount: 100, unit: 'g', label: '100 grams' },
          { amount: 150, unit: 'portion', label: '1 Plate Portion (150g)' },
        ],
        calories: 240,
        protein: 14.5,
        carbohydrates: 6.2,
        fat: 17.8,
        fiber: 1.1,
        sugar: 2.0,
        sodium: 410,
        vitaminsAndMinerals: [
          { name: 'Calcium', amount: 380, unit: 'mg', dailyValuePercentage: 38 },
          { name: 'Phosphorus', amount: 260, unit: 'mg', dailyValuePercentage: 26 },
          { name: 'Vitamin A', amount: 310, unit: 'IU', dailyValuePercentage: 6 },
          { name: 'Vitamin B12', amount: 0.5, unit: 'mcg', dailyValuePercentage: 21 },
        ],
        dataSource: 'Indian Food Composition Tables',
        isVerified: true,
      },
      {
        name: 'Rolled Oats (Cooked with Water)',
        category: 'Grains & Cereals',
        brand: 'Quaker',
        servingSize: 100,
        servingUnit: 'g',
        servingOptions: [
          { amount: 100, unit: 'g', label: '100 grams' },
          { amount: 234, unit: 'cup', label: '1 Cooked Cup (234g)' },
        ],
        calories: 71,
        protein: 2.5,
        carbohydrates: 12.0,
        fat: 1.4,
        fiber: 1.7,
        sugar: 0.3,
        sodium: 4,
        vitaminsAndMinerals: [
          { name: 'Beta-Glucan Fiber', amount: 1.2, unit: 'g', dailyValuePercentage: 40 },
          { name: 'Manganese', amount: 0.56, unit: 'mg', dailyValuePercentage: 28 },
          { name: 'Phosphorus', amount: 77, unit: 'mg', dailyValuePercentage: 8 },
          { name: 'Iron', amount: 0.9, unit: 'mg', dailyValuePercentage: 5 },
          { name: 'Magnesium', amount: 26, unit: 'mg', dailyValuePercentage: 6 },
        ],
        dataSource: 'USDA FoodData Central',
        isVerified: true,
      },
      {
        name: 'Raw Almonds',
        category: 'Nuts & Seeds',
        brand: 'Nutri Choice',
        servingSize: 28,
        servingUnit: 'g',
        servingOptions: [
          { amount: 28, unit: 'oz', label: '1 oz / 23 Almonds (28g)' },
          { amount: 100, unit: 'g', label: '100 grams' },
        ],
        calories: 164,
        protein: 6.0,
        carbohydrates: 6.1,
        fat: 14.2,
        fiber: 3.5,
        sugar: 1.2,
        sodium: 1,
        vitaminsAndMinerals: [
          { name: 'Vitamin E', amount: 7.27, unit: 'mg', dailyValuePercentage: 48 },
          { name: 'Manganese', amount: 0.62, unit: 'mg', dailyValuePercentage: 27 },
          { name: 'Magnesium', amount: 76.5, unit: 'mg', dailyValuePercentage: 18 },
          { name: 'Copper', amount: 0.29, unit: 'mg', dailyValuePercentage: 32 },
          { name: 'Riboflavin (B2)', amount: 0.32, unit: 'mg', dailyValuePercentage: 25 },
          { name: 'Calcium', amount: 76, unit: 'mg', dailyValuePercentage: 8 },
        ],
        dataSource: 'USDA FoodData Central',
        isVerified: true,
      },
    ];

    await FoodModel.insertMany(foodsData);
    console.log(`✅ Seeded ${foodsData.length} items into Food Nutrition Database.`);
  } catch (error) {
    console.error('⚠️ Error seeding food database:', error);
  }
};
